django-todo/core/urls.py
from django.contrib import admin
from django.urls import path
from todo.views import complete_todo, get_todo_list, get_completed_todo_list, get_progress_todo_list, init_db
from todo.views import TodoDetailView, TodoCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_todo_list, name="todo_list"),
    path('completed/', get_completed_todo_list, name="completed_todo_list"),
    path('progress/', get_progress_todo_list, name="progress_todo_list"),
    path('create/', TodoCreateView.as_view(), name="create_todo"),
    path('<int:todo_id>/', TodoDetailView.as_view(), name="todo_detail"),
    path('<int:todo_id>/complete/', complete_todo, name="todo_complete"),
    path('init/', init_db),
]

django-todo/todo/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.forms.models import model_to_dict
from django.utils.translation import gettext_lazy as _

from enum import Enum


class Mark(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100,
                            verbose_name=_('Название'))

    def __unicode__(self):
        return str(self.name)

    def __str__(self):
        return str(self.name)

    def __repr__(self):
        return str(self.to_dict())

    def to_dict(self):
        return model_to_dict(self, fields=[field.name for field in self._meta.fields])

    class Meta:
        verbose_name = 'Метка'
        verbose_name_plural = 'Метки'
        db_table = 'db_mark'


class TaskStatus(Enum):
    PROGRESS = _("В процессе")
    COMPLETED = _("Выполнено")

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)


class Task(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150,
                             verbose_name=_('Задача'))
    description = models.TextField(blank=True,
                                   verbose_name=_('Описание'))
    created = models.DateField(default=timezone.now().strftime("%Y-%m-%d"),
                               verbose_name=_('Создано'))
    deadline = models.DateField(default=timezone.now().strftime("%Y-%m-%d"),
                                verbose_name=_('Дедлайн'))
    mark = models.ForeignKey(Mark,
                             on_delete=models.CASCADE,
                             default="general",
                             verbose_name=_('Метка'))
    status = models.CharField(max_length=15,
                              choices=TaskStatus.choices(),
                              default=TaskStatus.PROGRESS.name,
                              verbose_name='Статус')

    @classmethod
    def create(cls, title, description):
        task = cls(title=title, description=description)
        return task

    def complete(self):
        self.status = TaskStatus.COMPLETED.name
        self.status
        return self

    def __unicode__(self):
        return str(self.title)

    def __str__(self):
        return str(self.title)

    def __repr__(self):
        return str(self.to_dict())

    def to_dict(self):
        return model_to_dict(self, fields=[field.name for field in self._meta.fields])

    class Meta:
        ordering = ["-created"]
        verbose_name = 'Задание'
        verbose_name_plural = 'Задание'
        db_table = 'db_task'

django-todo/todo/forms.py
from django import forms
from .models import Task


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'deadline', 'mark', 'status')


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'deadline', 'mark',)

django-todo/todo/views.py
from __future__ import unicode_literals
from django.http import HttpResponseServerError
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.decorators.http import require_http_methods
from django.utils import timezone
from django.urls import reverse
from django.views import View

from .models import Mark, Task, TaskStatus
from .forms import TaskUpdateForm, TaskCreateForm


@require_http_methods(["GET"])
def get_todo_list(request):
    todo_list = Task.objects.all()
    return render_list_from_queryset(request, todo_list)


@require_http_methods(["GET"])
def get_progress_todo_list(request):
    todo_list = Task.objects.filter(status=TaskStatus.PROGRESS.name)
    return render_list_from_queryset(request, todo_list)


@require_http_methods(["GET"])
def get_completed_todo_list(request):
    todo_list = Task.objects.filter(status=TaskStatus.COMPLETED.name)
    return render_list_from_queryset(request, todo_list)


def render_list_from_queryset(request, todo_queryset):
    return render(request, "todo_list.html", {"todo_list": todo_queryset})


def complete_todo(request, todo_id: int):
    task = Task.objects.get(pk=todo_id)
    task.complete()
    task.save()
    return redirect(reverse('todo_list'))


class TodoCreateView(View):
    template_name = 'todo_create.html'

    def get(self, request):
        form = TaskCreateForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = TaskCreateForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.created = timezone.now()
            task.status = TaskStatus.PROGRESS.value
            task.save()
            return redirect(reverse('todo_list'))
        else:
            return HttpResponseServerError("Error form isn't valid: %s" % form.errors)


class TodoDetailView(View):
    http_method_names = ['get', 'post', 'put', 'delete']
    template_name = 'todo_detail.html'
    todo_id = None

    def dispatch(self, *args, **kwargs):
        method = self.request.POST.get('_method', '').lower()
        if method == 'put':
            return self.put(*args, **kwargs)
        if method == 'delete':
            return self.delete(*args, **kwargs)
        return super(TodoDetailView, self).dispatch(*args, **kwargs)

    def get(self, request, todo_id: int):
        todo = get_object_or_404(Task, pk=todo_id)
        form = TaskUpdateForm(initial=todo.to_dict())
        return render(request, self.template_name, {"todo": todo, "form": form})

    @staticmethod
    def put(request, todo_id: int):
        instance = get_object_or_404(Task, id=todo_id)
        form = TaskUpdateForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse('todo_list'))
        else:
            return HttpResponseServerError("Error form isn't valid: %s" % form.errors)

    @staticmethod
    def delete(request, todo_id: int):
        Task.objects.filter(pk=todo_id).delete()
        return redirect(reverse('todo_list'))


def init_db(request):
    Mark.objects.all().delete()
    Task.objects.all().delete()

    mark_home = Mark.objects.create(name="Дом")
    mark_work = Mark.objects.create(name="Работа")
    mark_uni = Mark.objects.create(name="Вуз")
    mark_product = Mark.objects.create(name="Продукты")

    task_arch = Task.objects.create(title="Сделать лабораторную по проектированию",
                                    description="Сделать лабораторную работу №7 и показать во вторник",
                                    mark=mark_uni)
    Task.objects.create(title="Купить молоко",
                        description="Купить в пятерочке пискоревское молоко",
                        mark=mark_product)
    Task.objects.create(title="Здать курсовую работу по вебу",
                        description="Доделать проект django-todo, составить отчет и сдать",
                        mark=mark_uni)
    Task.objects.create(title="Получить зарплату",
                        description="Не забыть получить зарплату во вторник с:",
                        mark=mark_work)
    task_table = Task.objects.create(title="Починить стол",
                                     description="-",
                                     mark=mark_home)
    task_arch.complete().save()
    task_table.complete().save()
    return redirect(reverse('todo_list'))

django-todo/todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Список задач</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'todo_list' %}">Сайт со списком задач</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Задачи<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'todo_list' %}">Все</a></li>
                        <li><a href="{% url 'completed_todo_list' %}">Выполненные</a></li>
                        <li><a href="{% url 'progress_todo_list' %}">В процессе</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="tg://resolve?domain=osipov_vadim>">
                        <span class="glyphicon glyphicon-send"></span>  Created by Osipov Vadim</a>
                </li>
                <li><a href="https://github.com/Osipov-Vadim/django-todo">
                        <span class="glyphicon glyphicon-link"></span>  Sourse Code</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>

</html>

django-todo/todo/templates/todo_create.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        <a href="{% url 'todo_list' %}" class="btn btn-default" role="button">Назад</a>
        <button type="submit" form="create_form" class="btn btn-success">Создать</button>
        <a href="{% url 'todo_list' %}" class="btn btn-danger" role="button">Отменить</a>
    </div>
</div>

<div class="container">
    <h2 class="page-header text-center">Создать задачу</h2>
    <!-- <form action="{% url 'create_todo' %}" method="POST" id="create_form">
        {% csrf_token %}
        {{ form.as_p }}
    </form> -->

    <form class="form-horizontal" action="{% url 'create_todo' %}" method="POST" id="create_form">
        {% csrf_token %}
        <!-- title -->
        <div class="form-group">
            <label class="control-label col-sm-2" for="id_title">Задача:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="title" maxlength="150" id="id_title">
                <span class="help-block">Введите краткое название задачи</span>
            </div>

        </div>
        <!-- description -->
        <div class="form-group">
            <label class="control-label col-sm-2" for="id_description">Описание:</label>
            <div class="col-sm-8">
                <textarea class="form-control" name="description" rows="7" id="id_description"></textarea>
                <span class="help-block">Подробно опишите задачу</span>
            </div>
        </div>
        <!-- date -->
        <div class="form-group">
            <label class="control-label col-sm-2" for="id_deadline">Дедлайн</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="deadline" id="id_deadline">
                <span class="help-block">Введите дедлайн в формате "год-месяц-день"</span>
            </div>
        </div>
        <!-- mark -->
        <div class="form-group">
            <label class="control-label col-sm-2" for="id_mark">Метка</label>
            <div class="col-sm-8">
                <select class="form-control" name="mark" id="id_mark">
                    {% for name, value in form.fields.mark.choices %}
                    <option value="{{ name }}">{{ value }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
</div>



</div>
{% endblock %}

django-todo/todo/templates/todo_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        <a href="{% url 'todo_list' %}" class="btn btn-default" role="button">Назад</a>
        <button type="submit" type="Post" form="update_form" class="btn btn-success">Сохранить</button>
        <button type="submit" type="Delete" form="delete_form" class="btn btn-danger">Удалить</button>
        <!-- <a href="{% url 'todo_detail' todo.id %}" value="POST" class="btn btn-danger" role="button">Удалить</a> -->
    </div>
</div>

<div class="container">
    <h2 class="page-header text-center">Все задачи</h2>
    <form action="{% url 'todo_detail' todo.id %}" method="post" class="task-form" id="update_form">
        {% csrf_token %}
        <input type="hidden" name="_method" value="put">
        {{ form.as_p }}
    </form>
    <form action="{% url 'todo_detail' todo.id %}" method="post" class="task-form" id="delete_form">
        {% csrf_token %}
        <input type="hidden" name="_method" value="delete">
    </form>
</div>
{% endblock %}

django-todo/todo/templates/todo_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        <a href="{% url 'create_todo' %}" class="btn btn-success" role="button">Создать задачу</a>
    </div>
</div>

<div class="container">
    <h2 class="page-header text-center">Список задач</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Заголовок</th>
                <th>Дедлайн</th>
                <th>Метка</th>
                <th>Статус</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todo_list %}
            <tr>
                <th>
                    <a href="{% url 'todo_detail' todo.id %}" class="text-info">{{ todo.title }}</a>
                </th>
                <th>
                    <p style="color:gray;">{{ todo.deadline }}</p>
                </th>
                <th>{{ todo.mark }}</th>

                {% if todo.status == "COMPLETED" %}
                <th>
                    <p>
                        <a href="{% url 'completed_todo_list' %}" style="color:green;">{{ todo.get_status_display }}</a>
                    </p>
                </th>
                <th></th>
                {% else %}
                <th>
                    <p>
                        <a href="{% url 'progress_todo_list' %}" style="color:red;">{{ todo.get_status_display }}</a>
                    </p>
                </th>
                <th><a href="{% url 'todo_complete' todo.id %}"> <span style="color:green;" class="glyphicon glyphicon-ok"></span></a></th>
                {% endif %}
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}